const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const state = { file:null, objectUrl:null, target:null, jobId:localStorage.getItem('footballScoutJobId'), pollTimer:null };
const panels={upload:$('#upload-panel'),player:$('#video-panel'),confirm:$('#confirm-panel'),progress:$('#progress-panel')}; const video=$('#video'), marker=$('#target-marker');
function formatTime(v){if(!Number.isFinite(v))return'—';const h=Math.floor(v/3600),m=Math.floor(v%3600/60),s=Math.floor(v%60).toString().padStart(2,'0');return h?`${h}:${m.toString().padStart(2,'0')}:${s}`:`${m}:${s}`}
function formatBytes(b){return b>=1024**3?`${(b/1024**3).toFixed(1)} Go`:`${(b/1024**2).toFixed(1)} Mo`}
function showToast(message,tone='error'){const t=$('#toast');t.textContent=message;t.dataset.tone=tone;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),5000)}
function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.nav-link').forEach(l=>l.classList.toggle('active',l.dataset.viewTarget===name));scrollTo({top:0,behavior:'smooth'})}
function showPanel(name){Object.entries(panels).forEach(([k,p])=>p.classList.toggle('hidden',k!==name));const order=['upload','player','confirm','progress'];$$('.steps li').forEach(i=>{const c=order.indexOf(name),o=order.indexOf(i.dataset.step);i.classList.toggle('active',o===c);i.classList.toggle('complete',o<c)})}
$$('[data-view-target]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.viewTarget)));
function resetSelection(){state.target=null;marker.classList.add('hidden');$('#selected-time').textContent='—';$('#selected-position').textContent='En attente';$('#clear-selection').disabled=true;$('#confirm-player').disabled=true;$('#selection-status').textContent='Clique sur le joueur pour continuer.';$('#video-hint').classList.remove('hidden')}
function loadVideo(file){if(!file||!file.type.startsWith('video/'))return showToast('Choisis un fichier vidéo compatible.');if(state.objectUrl)URL.revokeObjectURL(state.objectUrl);state.file=file;state.objectUrl=URL.createObjectURL(file);video.src=state.objectUrl;$('#file-name').textContent=file.name;$('#file-meta').textContent=formatBytes(file.size);resetSelection();showPanel('player')}
$('#video-input').addEventListener('change',e=>loadVideo(e.target.files?.[0]));['dragenter','dragover'].forEach(n=>$('#dropzone').addEventListener(n,e=>{e.preventDefault();$('#dropzone').classList.add('dragging')}));['dragleave','drop'].forEach(n=>$('#dropzone').addEventListener(n,e=>{e.preventDefault();$('#dropzone').classList.remove('dragging')}));$('#dropzone').addEventListener('drop',e=>loadVideo(e.dataTransfer?.files?.[0]));$('#replace-video').addEventListener('click',()=>{$('#video-input').click()});$('#clear-selection').addEventListener('click',resetSelection);$('#back-to-player').addEventListener('click',()=>showPanel('player'));
video.addEventListener('loadedmetadata',()=>{$('#file-meta').textContent=`${formatBytes(state.file.size)} · ${formatTime(video.duration)}`});
$('#video-stage').addEventListener('click',event=>{if(!state.file||video.readyState<2)return;const rect=video.getBoundingClientRect(),vr=video.videoWidth/video.videoHeight,er=rect.width/rect.height;let width=rect.width,height=rect.height,offsetX=0,offsetY=0;if(er>vr){width=rect.height*vr;offsetX=(rect.width-width)/2}else{height=rect.width/vr;offsetY=(rect.height-height)/2}const x=event.clientX-rect.left-offsetX,y=event.clientY-rect.top-offsetY;if(x<0||y<0||x>width||y>height)return;video.pause();state.target={x:x/width,y:y/height,time:video.currentTime};marker.style.left=`${offsetX+x}px`;marker.style.top=`${offsetY+y}px`;marker.classList.remove('hidden');$('#video-hint').classList.add('hidden');$('#selected-time').textContent=formatTime(state.target.time);$('#selected-position').textContent=`${(state.target.x*100).toFixed(1)} % · ${(state.target.y*100).toFixed(1)} %`;$('#clear-selection').disabled=false;$('#confirm-player').disabled=false;$('#selection-status').textContent='✓ Joueur sélectionné. Vérifie le repère puis confirme.';$('#summary-file').textContent=state.file.name;$('#summary-duration').textContent=formatTime(video.duration);$('#summary-time').textContent=formatTime(state.target.time)});
$('#confirm-player').addEventListener('click',()=>{if(!state.target)return showToast('Clique d’abord sur le joueur.');showPanel('confirm')});
const savedApi=localStorage.getItem('footballScoutApiBase'); if(savedApi)$('#api-base').value=savedApi; $('#api-base').addEventListener('change',()=>localStorage.setItem('footballScoutApiBase',$('#api-base').value.trim()));
function apiBase(){return $('#api-base').value.trim().replace(/\/$/,'')}async function api(path,options={}){if(!apiBase())throw new Error('Le backend de production n’est pas encore configuré');const r=await fetch(`${apiBase()}${path}`,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(typeof b.detail==='string'?b.detail:b.detail?.message||`Erreur serveur (${r.status})`);return b}
function idempotencyKey(){const e=sessionStorage.getItem('footballScoutIdempotencyKey');if(e)return e;const k=crypto.randomUUID();sessionStorage.setItem('footballScoutIdempotencyKey',k);return k}
$('#start-analysis').addEventListener('click',async()=>{const button=$('#start-analysis'),videoUrl=$('#video-url').value.trim();if(!state.target||!Number.isFinite(video.duration))return showToast('Sélectionne d’abord le joueur.');if(!apiBase())return showToast('Le moteur en ligne n’est pas encore connecté à cette version du site.');if(!videoUrl)return showToast('Le stockage vidéo sécurisé doit être connecté avant le lancement.');button.disabled=true;button.textContent='Vérification…';try{const estimate=await api('/analysis/estimate',{method:'POST',body:JSON.stringify({video_duration_seconds:video.duration})});if(!estimate.ready)throw new Error('Le benchmark de coût requis n’est pas encore disponible. Aucun GPU n’a été lancé.');const max=Number(estimate.recommended_max_authorization_usd);$('#estimate-box').innerHTML=`<strong>Estimation validée</strong><span>Plafond recommandé : ${max.toFixed(2)} $</span>`;$('#estimate-box').classList.remove('hidden');const payload={video_url:videoUrl,video_duration_seconds:video.duration,target_time_seconds:state.target.time,target:{x:state.target.x,y:state.target.y},sample_fps:5,confidence:.22,image_size:960,approved_max_cost_usd:max};const submitted=await api('/analysis/submit',{method:'POST',headers:{'X-Idempotency-Key':idempotencyKey(),'X-Cost-Approval-Secret':$('#cost-secret').value},body:JSON.stringify(payload)});state.jobId=submitted.job.job_id;localStorage.setItem('footballScoutJobId',state.jobId);$('#resume-job').hidden=false;showPanel('progress');updateProgress(submitted.job.status);pollJob()}catch(e){showToast(e.message)}finally{button.disabled=false;button.innerHTML='Vérifier et lancer <span>→</span>'}});
function updateProgress(status){const values={submitted:[12,'Envoi sécurisé'],queued:[24,'Dans la file d’attente'],running:[66,'Suivi du joueur'],completed:[100,'Rapport prêt']};const[p,l]=values[status]||[18,'Préparation'];$('#progress-bar').style.width=`${p}%`;$('#progress-percent').textContent=`${p} %`;$('#progress-state').textContent=l;$('#progress-title').textContent=status==='running'?'Le moteur suit le joueur sélectionné.':status==='queued'?'Ton match est dans la file d’attente.':'Préparation de l’analyse.';$('#stage-tracking').classList.toggle('done',p>=66);$('#stage-quality').classList.toggle('done',p>=85);$('#stage-report').classList.toggle('done',p===100)}
async function pollJob(){clearTimeout(state.pollTimer);if(!state.jobId)return;try{const job=await api(`/analysis/jobs/${encodeURIComponent(state.jobId)}/refresh`,{method:'POST'});updateProgress(job.status);if(job.status==='completed'&&job.result)return renderResult(job.result);if(['failed','timed_out','cancelled'].includes(job.status))return renderFailure('Le traitement n’a pas abouti','Aucune statistique n’est affichée.');state.pollTimer=setTimeout(pollJob,3500)}catch(e){renderFailure('Impossible de suivre l’analyse',`${e.message}. Aucun nouvel envoi n’a été effectué.`)}}
function metricCard(title,metric,formatter,reason){if(!metric?.available)return `<article class="metric-card locked"><span>${title}</span><strong>Masquée</strong><small>🔒 ${reason}</small></article>`;return `<article class="metric-card"><span>${title}</span><strong>${formatter(metric.value)}</strong><small>✓ Contrôle de fiabilité passé</small></article>`}
function renderResult(result){clearTimeout(state.pollTimer);showView('results');if(result.status!=='ready')return renderFailure('Analyse non exploitable','Le suivi du joueur n’a pas franchi tous les contrôles. Les statistiques sont volontairement masquées.',result);const m=result.metrics||{},q=result.quality||{};$('#result-content').innerHTML=`<div class="result-head"><div><p class="eyebrow">RAPPORT JOUEUR</p><h1>Analyse terminée.</h1><p>Seules les métriques ayant franchi leur contrôle sont affichées.</p></div><span class="quality-pill">✓ Suivi validé</span></div><div class="result-summary"><div class="quality-score"><span>Qualité du suivi</span><strong>${Number(q.player_tracking_score_percent).toFixed(0)}<small>%</small></strong><p>Couverture : ${Number(q.tracking_coverage_percent).toFixed(1)} %</p></div><div class="metrics-grid">${metricCard('Distance parcourue',m.distance_meters,v=>`${(v/1000).toFixed(2).replace('.',',')} km`,'Calibration terrain requise')}${metricCard('Touches de balle',m.ball_touches,v=>String(v),'Visibilité ballon insuffisante')}${metricCard('Temps de possession',m.possession_seconds,v=>formatTime(v),'Contrôle ballon non atteint')}</div></div><section class="quality-explain"><div><p class="eyebrow">TRANSPARENCE</p><h2>Pourquoi certaines données sont masquées</h2><p>La distance exige une calibration valide. Les touches et la possession exigent un suivi fiable du ballon.</p></div><div class="gate-list"><span class="pass">✓ Continuité joueur</span><span class="${q.ball_metrics_pass?'pass':'locked'}">${q.ball_metrics_pass?'✓':'—'} Ballon</span><span class="${q.pitch_calibration_used?'pass':'locked'}">${q.pitch_calibration_used?'✓':'—'} Calibration</span></div></section><div class="action-row"><button class="secondary" id="new-analysis">Nouvelle analyse</button></div>`;$('#new-analysis').addEventListener('click',newAnalysis)}
function renderFailure(title,message,result=null){showView('results');const coverage=result?.quality?.tracking_coverage_percent;$('#result-content').innerHTML=`<div class="failure-card"><div class="failure-icon">!</div><p class="eyebrow">RÉSULTAT PROTÉGÉ</p><h1>${title}</h1><p>${message}</p>${Number.isFinite(coverage)?`<div class="diagnostic">Couverture détectée : <strong>${coverage.toFixed(1)} %</strong><small>Indicateur technique, pas une statistique de performance.</small></div>`:''}<button class="primary" id="retry-analysis">Préparer une nouvelle analyse</button></div>`;$('#retry-analysis').addEventListener('click',newAnalysis)}
function newAnalysis(){localStorage.removeItem('footballScoutJobId');sessionStorage.removeItem('footballScoutIdempotencyKey');state.jobId=null;$('#resume-job').hidden=true;showView('analysis');showPanel('upload')}
$('#stop-polling').addEventListener('click',()=>{clearTimeout(state.pollTimer);showToast('Suivi à l’écran arrêté. Le job n’a pas été relancé.','info')});$('#resume-job').addEventListener('click',()=>{showView('analysis');showPanel('progress');pollJob()});if(state.jobId)$('#resume-job').hidden=false;addEventListener('beforeunload',()=>{if(state.objectUrl)URL.revokeObjectURL(state.objectUrl);clearTimeout(state.pollTimer)});